Repository AY2223S1-CS2103T-T14-2/tp, pull requests merged in 2022-11, with the labels that each got.

#153 fix bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
Labels: priority.Medium

#159 Updated message success of list task command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/DeadlineComparator.java
  src/main/java/seedu/address/model/task/DefaultComparator.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableTaskListTest/duplicateTaskTaskList.json
  src/test/data/JsonSerializableTaskListTest/invalidTaskTaskList.json
  src/test/data/JsonSerializableTaskListTest/typicalTasksTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidAndValidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/notJsonFormatTaskList.json
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/model/task/DeadlineComparatorTest.java
  src/test/java/seedu/address/model/task/DefaultComparatorTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
Labels: priority.Low

#161 Change Help command message
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#166 Bug fix and README update
  README.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/model/person/CanHelpWithTaskPredicate.java
Labels: type.Bug, documentation

#168 update UG and PPP
  docs/UserGuide.md
  docs/team/danzzzerl.md
Labels: documentation

#171 UG updates (Parnikkapore)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/diagrams/AddTaskCommandSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/AddTaskCommandSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/team/parnikkapore.md
  src/main/java/seedu/address/model/task/Deadline.java
Labels: documentation

#169 UG/DG/PPP Updates
  docs/UserGuide.md
  docs/images/UiAnnotated.png
  docs/team/jonlamy.md
Labels: documentation

#173 Make UI change data file according to tab
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Low

#170 Improve user input handling for `find` and `findc`
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/person/ModuleTakenPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsModulesPredicate.java
Labels: type.Bug

#177 Improve user stories
  docs/DeveloperGuide.md
Labels: documentation

#178 Fix issue of path not updating on tab click
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.Low

#179 Improve code quality and update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/danzzzerl.md
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/parser/CodeConnectParser.java
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
Labels: documentation, priority.Low

#183 update DG
  docs/UserGuide.md
Labels: documentation

#180 Add manual testing guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#190 Update page break
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/songivan00.md
  src/main/java/seedu/codeconnect/MainApp.java
Labels: documentation

#191 Slightly improve UG/DG formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
