Repository AY2223S1-CS2103T-T14-2/tp, pull requests merged in 2022-10, with the labels that each got.

#49 Implement `findc` feature to find contacts
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditContactCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/person/Mods.java
  src/main/java/seedu/address/model/person/ModuleTakenPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindContactCommandParserTest.java
  src/test/java/seedu/address/model/person/ModuleTakenPredicateTest.java
  src/test/java/seedu/address/model/task/ModuleTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story

#57 Find feature updated
  docs/UserGuide.md
  docs/team/danzzzerl.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsModulesPredicate.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskContainsModulesPredicateTest.java
Labels: priority.3

#59 Seperate task and person list into seperate tabs
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: enhancement

#62 [Parnikkkapore] Update documentation and PPP
  docs/UserGuide.md
  docs/team/parnikkapore.md
Labels: documentation

#63 Update UG and README
  README.md
  build.gradle
  docs/UserGuide.md
Labels: documentation

#74 Add Find Command section to User Guide
  docs/DeveloperGuide.md
  docs/diagrams/FindContactActivityDiagram.puml
  docs/diagrams/FindContactSequenceDiagram.puml
  docs/images/FindContactActivityDiagram.png
  docs/images/FindContactExample.png
  docs/images/FindContactSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
Labels: documentation

#77 Edit DG danzzzerl
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindContactSequenceDiagram.puml
  docs/diagrams/FindTasksSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/FindContactSequenceDiagram.png
  docs/images/FindTasksSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/angkl0.md
  docs/team/danzzzerl.md
  docs/team/songivan00.md
Labels: documentation

#78 Add add command docs to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskCommandSequenceDiagram.puml
  docs/images/AddTaskCommandSequenceDiagram.png
Labels: documentation

#75 Update songivan00 dg
  docs/DeveloperGuide.md
  docs/diagrams/EditTaskActivityDiagram.puml
  docs/images/EditTaskActivityDiagram.png
Labels: documentation

#84 Edit task command
  README.md
  docs/UserGuide.md
  docs/team/songivan00.md
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: documentation, priority.Medium

#85 Add natural date parsing
  README.md
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/parnikkapore.md
  src/main/java/seedu/address/commons/util/NaturalDateParser.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/test/java/seedu/address/commons/util/NaturalDateParserTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.Medium

#90 Implement listing of tasks according to deadline
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/DeadlineComparator.java
  src/main/java/seedu/address/model/task/DefaultComparator.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/DeadlineComparatorTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
Labels: priority.Medium

#89 Add find contact by task features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/CanHelpWithTaskPredicate.java
  src/main/java/seedu/address/model/person/ModuleTakenPredicate.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindContactCommandParserTest.java
  src/test/java/seedu/address/model/person/CanHelpWithTaskPredicateTest.java
Labels: priority.High

#92 make modules field optional for tasks
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/ModuleTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.Medium

#96 Space-separated module parsing
  README.md
  docs/UserGuide.md
  docs/team/parnikkapore.md
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
Labels: type.Enhancement

#98 Improve find command
  docs/UserGuide.md
  docs/team/angkl0.md
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/person/ModuleTakenPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsModulesPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/ModuleTakenPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskContainsModulesPredicateTest.java
Labels: type.Enhancement, priority.Medium

#94 Change some fields in contacts to be optional
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#100 Edit UG consistency
  docs/UserGuide.md
  docs/images/UiContacts.png
  docs/images/UiTasks.png
  docs/index.md
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#142 Edit front matters of the UG
  docs/UserGuide.md
Labels: documentation

#140 Improve UG styling and readability
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
Labels: documentation

#147 Update user guide
  docs/UserGuide.md
Labels: documentation

#149 update ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/editContact.png
  docs/images/findTaskModule.png
  docs/images/markTask.png
  docs/team/angkl0.md
  docs/team/songivan00.md
Labels: documentation

#150 Update ug
  docs/UserGuide.md
Labels: documentation

#152 Fix JChronic example inaccuracies
  docs/UserGuide.md
Labels: documentation
